# Generated by Django 5.1.6 on 2025-02-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_logo_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.TextField(help_text="Value of the attribute like 'Vitamin C', 'Wood', 'Large'"),
        ),
    ]
